import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property bool inverted
    property int numberOfFrames
    property int period
    property string size
    property url spinnerFrames
}
