import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant flick
    property int index
    property bool offScreen
    property variant platformStyle
    property bool running
    property variant style
}
