import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant checkedButton
    property bool exclusive
    property variant platformStyle
    property variant style
}
