import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property url background
    property int backgroundMarginBottom
    property int backgroundMarginLeft
    property int backgroundMarginRight
    property int backgroundMarginTop
    property int buttonHeight
    property int buttonWidth
    property url checkedBackground
    property url checkedDisabledBackground
    property int checkedFontWeight
    property color checkedTextColor
    property url dialog
    property url disabledBackground
    property color disabledTextColor
    property int fontCapitalization
    property string fontFamily
    property int fontPixelSize
    property int fontWeight
    property int horizontalAlignment
    property bool inverted
    property real mouseMarginBottom
    property real mouseMarginLeft
    property real mouseMarginRight
    property real mouseMarginTop
    property string position
    property url pressedBackground
    property url pressedDialog
    property color pressedTextColor
    property color textColor
}
