import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Text {
    property bool checked
    property variant platformMouseAnchors
    property variant platformStyle
    property bool pressed
    signal clicked()
}
