import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant platformStyle
    property variant pressed
    property variant style
    property string text
    signal clicked()
}
