import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property int maxHeight
    property variant oldParent
    property variant platformStyle
    property variant platformTitle
    property int status
    property variant style
    property variant title
    property variant visualParent
    signal clicked()
    signal privateClicked()
    function close() {}
    function closeMenu() {}
    function open() {}
}
