import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property bool busy
    property bool cleanupAfterTransition
    property variant currentPage
    property int depth
    property variant owner
    property variant page
    property variant toolBar
    property int transitionDuration
    function cleanup() {}
    function clear() {}
    function find(func) {}
    function pop(page, immediate) {}
    function popEnter(immediate) {}
    function popExit(immediate) {}
    function push(page, properties, immediate) {}
    function pushEnter(replace, immediate) {}
    function pushExit(replace, immediate) {}
    function replace(page, properties, immediate) {}
    function transitionEnded() {}
    function transitionStarted() {}
}
