import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property bool animating
    property variant color
    property int heightDelta
    property variant inPortrait
    property variant initialPage
    property variant pageStack
    property variant platformStyle
    property variant platformToolBarHeight
    property bool portrait
    property bool showStatusBar
    property bool showToolBar
    property variant softwareInputPanelRect
    property variant style
    signal orientationChangeAboutToStart()
    signal orientationChangeFinished()
    signal orientationChangeStarted()
    function updateWindowContentHeightDelta() {}
}
