import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant flick
    property bool indeterminate
    property variant maximumValue
    property variant minimumValue
    property bool offScreen
    property variant platformStyle
    property variant style
    property variant value
}
