import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant acceptButtonText
    property variant buttons
    property variant content
    property variant icon
    property string message
    property variant oldParent
    property variant platformStyle
    property variant rejectButtonText
    property int status
    property variant style
    property variant title
    property string titleText
    property int upperBound
    property variant visualParent
    signal accepted()
    signal clicked()
    signal linkActivated(string link)
    signal privateClicked()
    signal rejected()
    function accept() {}
    function close() {}
    function open() {}
    function reject() {}
}
