import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant flickableItem
    property variant platformStyle
    property bool shouldShow
    property variant style
    function canFlick(direction) {}
}
