import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant buttons
    property variant content
    property variant delegate
    property int listViewHeight
    property int maxListViewHeight
    property variant model
    property variant oldParent
    property variant platformStyle
    property bool selected
    property int selectedIndex
    property int status
    property variant style
    property variant title
    property string titleText
    property variant visualParent
    signal accepted()
    signal clicked()
    signal privateClicked()
    signal rejected()
    function accept() {}
    function close() {}
    function open() {}
    function reject() {}
}
