import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant acceptButton
    property variant acceptButtonText
    property variant buttons
    property variant content
    property variant platformStyle
    property variant rejectButton
    property variant rejectButtonText
    property int status
    property int statusBarOffset
    property variant style
    property variant title
    property int transitionDurationIn
    property int transitionDurationOut
    property variant visualParent
    signal accepted()
    signal rejected()
    function accept() {}
    function close() {}
    function getButton(name) {}
    function open() {}
    function reject() {}
    function transitionEnded() {}
    function transitionStarted() {}
}
