import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant inverted
    property variant maximumValue
    property variant minimumValue
    property real oldPosition
    property int orientation
    property variant platformMouseAnchors
    property variant pressed
    property variant stepSize
    property variant value
    property int valueIndicatorMargin
    property string valueIndicatorPosition
    property string valueIndicatorText
    property bool valueIndicatorVisible
    function formatValue(v) {}
}
