import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
TextInput {
    property bool attemptToActivate
    property variant customSoftwareInputPanel
    property variant editBubblePosition
    property variant enableSoftwareInputPanel
    property bool errorHighlight
    property int oldCursorPosition
    property variant placeholderText
    property variant platformCustomSoftwareInputPanel
    property bool platformEnableEditBubble
    property variant platformPreedit
    property bool platformSelectable
    property variant platformSipAttributes
    property variant platformStyle
    property variant platformWesternNumericInputEnforced
    property variant preedit
    property variant preeditCursorPosition
    property bool pressOnPreedit
    property variant style
    property bool suppressInputMethod
    property bool westernNumericInputEnforced
    signal accepted()
    function closeSoftwareInputPanel() {}
    function copy() {}
    function cut() {}
    function forceActiveFocus() {}
    function openSoftwareInputPanel() {}
    function paste() {}
    function platformCloseSoftwareInputPanel() {}
    function platformOpenSoftwareInputPanel() {}
    function positionAt(x) {}
    function positionToRectangle(pos) {}
    function select(start, end) {}
    function selectAll() {}
    function selectWord() {}
}
