import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property url background
    property real backgroundCornerMargin
    property url backgroundDisabled
    property url backgroundError
    property url backgroundSelected
    property real baselineOffset
    property real defaultWidth
    property real paddingLeft
    property real paddingRight
    property color promptTextColor
    property color selectedTextColor
    property color selectionColor
    property color textColor
    property variant textFont
    property real touchExpansionMargin
}
