import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property variant owner
    property variant platformStyle
    property int privateVisibility
    property variant style
    property variant tools
    property string transition
    function setTools(tools, transition) {}
}
