import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property bool animating
    property variant color
    property int heightDelta
    property variant inPortrait
    property bool portrait
    property variant softwareInputPanelRect
    signal orientationChangeAboutToStart()
    signal orientationChangeFinished()
    signal orientationChangeStarted()
    function updateWindowContentHeightDelta() {}
}
