#!/bin/sh
# Writes meego/tests/stubs/com/nokia/meego from the real components.
#
# The checker (meego/tests/qml_check.cpp) needs com.nokia.meego to exist, and
# the real one cannot be loaded here: its plugin is built for the SDK's
# Qt 4.7.4, which aborts without a display, and Qt 4.8.1 refuses a plugin built
# for another version. Hand-written stand-ins were worse than nothing -- they
# accepted properties the real components do not have (backNavigation, say),
# so the checker passed and the device would not.
#
# So the stand-ins are generated from the real sources in the SDK: every
# property, signal and function each component declares, with an Item (or a
# TextInput/TextEdit where the pages reach into a font) underneath. They are
# checked in, so the check runs anywhere; re-run this when the SDK moves.
#
#   meego/tests/make-stubs.sh [path to com/nokia/meego]
set -e

HERE=$(cd "$(dirname "$0")/../.." && pwd)
SRC=${1:-$HOME/QtSDK/Desktop/Qt/474/gcc/imports/com/nokia/meego}
OUT=$HERE/meego/tests/stubs/com/nokia/meego

[ -f "$SRC/qmldir" ] || { echo "com.nokia.meego not found at $SRC" >&2; exit 2; }

mkdir -p "$OUT"
python3 - "$SRC" "$OUT" <<'PY'
import os
import re
import sys

src, out = sys.argv[1], sys.argv[2]

# The types the port uses, and what a stand-in for each has to be underneath.
# TextField/TextArea carry a font the pages set with grouped notation, so they
# need a real text item rather than an Item.
BASE = {
    "TextField": "TextInput",
    "TextArea": "TextEdit",
    "MenuLayout": "Column",
    # Label ist in Wahrheit ein Text: die Seiten setzen horizontalAlignment,
    # wrapMode und elide darauf. Button und ToolButton tragen eine Schrift,
    # auf die mit font.pixelSize zugegriffen wird -- unter einem blanken Item
    # gibt es die Gruppe "font" nicht.
    "Label": "Text",
    "Button": "Text",
    "ToolButton": "Text",
    "CheckBox": "Text",
    "Switch": "Text",
}
TYPES = ["Page", "PageStack", "PageStackWindow", "Menu", "MenuLayout", "MenuItem",
         "Button", "Switch", "TextField", "TextArea", "Slider", "SliderTemplate",
         "BusyIndicator", "BusyIndicatorStyle", "SelectionDialog", "Sheet",
         "ToolBar", "ToolIcon", "ProgressBar", "ScrollDecorator", "Label",
         "Dialog", "CommonDialog", "QueryDialog", "Window",
         # Tarock benutzt zusätzlich diese.
         "ButtonRow", "ToolBarLayout", "CheckBox", "ButtonColumn", "ToolButton",
         "ToolButtonRow", "ButtonStyle", "TextFieldStyle"]

# Property types an Item-based stand-in can carry as they are. Anything else
# (Style, Item, Flickable, alias to something unknown) becomes a variant.
PLAIN = {"bool", "int", "real", "double", "string", "url", "color", "variant", "font"}

PROPERTY = re.compile(r'^\s*property\s+(\w+)\s+(\w+)\s*(?::(.*))?$')
ALIAS = re.compile(r'^\s*property\s+alias\s+(\w+)\s*:\s*(.*)$')
SIGNAL = re.compile(r'^\s*signal\s+(\w+)\s*(\([^)]*\))?\s*$')
FUNCTION = re.compile(r'^\s*function\s+(\w+)\s*\(([^)]*)\)')
BASETYPE = re.compile(r'^([A-Z]\w*)\s*\{\s*$')


def read(name):
    path = os.path.join(src, name + ".qml")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return f.read().splitlines()


def collect(name, seen=None):
    """Everything the component declares, following its base type."""
    seen = seen or set()
    if name in seen:
        return {}, [], []
    seen.add(name)

    lines = read(name)
    if lines is None:
        return {}, [], []

    props, signals, functions = {}, [], []
    base = None
    for line in lines:
        if base is None:
            m = BASETYPE.match(line)
            if m and m.group(1) not in ("Item",):
                base = m.group(1)

        m = ALIAS.match(line)
        if m and not m.group(1).startswith("__"):
            # The alias target's type is not knowable here; the pages that need
            # a real one (font) get it from the base item below.
            props[m.group(1)] = "variant"
            continue
        m = PROPERTY.match(line)
        if m and not m.group(2).startswith("__"):
            kind, prop = m.group(1), m.group(2)
            props[prop] = kind if kind in PLAIN else "variant"
            continue
        m = SIGNAL.match(line)
        if m:
            signals.append((m.group(1), m.group(2) or "()"))
            continue
        m = FUNCTION.match(line)
        if m and not m.group(1).startswith("__"):
            functions.append((m.group(1), m.group(2)))

    # A component's own declarations win over the ones it inherits.
    if base and base not in ("Rectangle", "FocusScope", "ImplicitSizeItem"):
        bprops, bsignals, bfunctions = collect(base, seen)
        bprops.update(props)
        props = bprops
        signals = bsignals + signals
        functions = bfunctions + functions
    elif base in ("FocusScope", "ImplicitSizeItem"):
        pass

    return props, signals, functions


header = ("import QtQuick 1.1\n"
          "// Generated by meego/tests/make-stubs.sh from the real component;\n"
          "// only the API surface, so that the checker sees what the device has.\n")

written = []
for name in TYPES:
    if read(name) is None:
        continue
    props, signals, functions = collect(name)
    base = BASE.get(name, "Item")

    # Properties a plain Item already has must not be redeclared.
    for builtin in ("anchors", "children", "data", "parent", "width", "height",
                    "visible", "opacity", "enabled", "x", "y", "z", "state",
                    "clip", "focus", "rotation", "scale", "smooth"):
        props.pop(builtin, None)
    if base in ("TextInput", "TextEdit"):
        for builtin in ("text", "font", "readOnly", "wrapMode", "cursorPosition",
                        "selectedText", "selectionStart", "selectionEnd",
                        "horizontalAlignment", "verticalAlignment", "inputMethodHints",
                        "validator", "acceptableInput", "inputMask", "maximumLength",
                        "echoMode", "textFormat", "color", "selectByMouse"):
            props.pop(builtin, None)
    if base == "Column":
        for builtin in ("spacing",):
            props.pop(builtin, None)
    if base == "Text":
        # Was ein Text von sich aus hat, darf die Attrappe nicht noch einmal
        # erklären -- sonst lehnt die Maschine sie ab.
        for builtin in ("text", "font", "color", "wrapMode", "elide", "lineHeight",
                        "horizontalAlignment", "verticalAlignment", "textFormat",
                        "style", "styleColor", "maximumLineCount", "lineCount",
                        "truncated", "paintedWidth", "paintedHeight"):
            props.pop(builtin, None)

    body = ["%s {" % base]
    for prop in sorted(props):
        body.append("    property %s %s" % (props[prop], prop))
    for signal, args in sorted(set(signals)):
        body.append("    signal %s%s" % (signal, args))
    for function, args in sorted(set(functions)):
        body.append("    function %s(%s) {}" % (function, args))
    body.append("}")

    with open(os.path.join(out, name + ".qml"), "w") as f:
        f.write(header + "\n".join(body) + "\n")
    written.append(name)

with open(os.path.join(out, "qmldir"), "w") as f:
    f.write("# Generated by meego/tests/make-stubs.sh -- see that script.\n")
    for name in written:
        f.write("%s 1.0 %s.qml\n" % (name, name))

print("%d stand-ins written" % len(written))
PY
